export const CARD_GAP = 20;
export const DESKTOP_CARD_CONTENT_WIDTH = 400;
export const MOBILE_CARD_CONTENT_WIDTH = 350;

export const DESKTOP_CARD_WIDTH = DESKTOP_CARD_CONTENT_WIDTH + CARD_GAP;
export const MOBILE_CARD_WIDTH = MOBILE_CARD_CONTENT_WIDTH + CARD_GAP;
