name: Run tests and upload coverage

on:
  push:
    branches:
      - main
      - develop-fe
  pull_request:
    branches:
      - main
      - develop-fe

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Run tests
        working-directory: frontend
        run: npx jest --coverage --config jest.config.js

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./frontend/coverage/lcov.info 
          flags: unittests
          name: codecov-coverage
          fail_ci_if_error: false
